version: "3.1"

services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgresa
    ports:
      - 5432:5432

  redis:
    hostname: redis
    container_name: redis
    image: redis:6.2.1-alpine
    restart: always
    ports:
      - 6379:6379

  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.9.3-community
    restart: always
    ports:
      - 9000:9000
      - 9092:9092
