version: "3.1"

networks:
  default:
    external:
      name: development

services:
  postgres:
    extends:
      file: postgres.yml
      service: postgres

  redis:
    extends:
      file: redis.yml
      service: redis

  mysql:
    extends:
      file: mysql.yml
      service: mysql
