version: "3.1"

services:
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devuser
      MYSQL_DATABASE: devuser
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
