version: "3.1"

services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:6.2.1-alpine
    restart: always
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
