version: "3.1"

services:
  redis:
    hostname: redis
    container_name: redis
    image: redis:6.2.1-alpine
    mem_limit: 128m
    mem_reservation: 64M
    cpus: 0.1
    restart: always
    environment:
      REDIS_PASSWORD: dev1122x
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
