version: "3.1"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.9.3-community
    restart: always
    volumes:
      - ./sonarqube_data/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_data/sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_data/sonarqube_temp:/opt/sonarqube/temp
    ports:
      - 9000:9000
      - 9092:9092
